"""MCP server (Streamable HTTP, JSON responses) exposing a connection's operations as tools.

URL: /mcp/{api_key}. The key is in the path because MCP clients such as claude.ai custom connectors
cannot attach custom auth headers. Tool calls run through the gateway, so cookies never reach the client.
"""
import json

from fastapi import APIRouter, Request, Response
from fastapi.responses import JSONResponse

from . import db, gateway

router = APIRouter()
SUPPORTED_VERSIONS = ["2025-11-25", "2025-06-18", "2025-03-26", "2024-11-05"]
JSON_TYPES = {"string", "integer", "number", "boolean", "array", "object"}


def tool_for(op, title):
    s = op["spec"]
    props = {}
    for p in s.get("params", []):
        t = str(p.get("type", "string")).lower()
        props[p["name"]] = {"type": t if t in JSON_TYPES else "string", "description": p.get("description", "")}
    effect = s.get("side_effect", "read")
    return {
        "name": op["name"],
        "title": f"{title}: {s.get('summary', op['name'])}"[:120],
        "description": s.get("description") or s.get("summary", ""),
        "inputSchema": {"type": "object", "properties": props,
                        "required": [p["name"] for p in s.get("params", []) if p.get("required")]},
        "annotations": {
            "readOnlyHint": effect == "read",
            "destructiveHint": effect == "irreversible_write",
            "idempotentHint": effect == "read",
            "openWorldHint": True,
        },
    }


def rpc_result(req_id, result):
    return {"jsonrpc": "2.0", "id": req_id, "result": result}


def rpc_error(req_id, code, message):
    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": code, "message": message}}


async def handle(msg, conn, base_url):
    method, req_id, params = msg.get("method"), msg.get("id"), msg.get("params") or {}
    site = db.get_site(conn["domain"])
    if method == "initialize":
        asked = params.get("protocolVersion")
        return rpc_result(req_id, {
            "protocolVersion": asked if asked in SUPPORTED_VERSIONS else SUPPORTED_VERSIONS[1],
            "capabilities": {"tools": {"listChanged": False}},
            "serverInfo": {"name": f"skeleton-key-{conn['domain']}", "version": "0.1.0"},
            "instructions": (f"Tools for the user's own {conn['domain']} account, generated by Skeleton Key. "
                             "Tools with destructiveHint change data irreversibly: ask the user first. If a tool "
                             "returns session_expired, give the user the reconnect_url so they can log in again."),
        })
    if method == "ping":
        return rpc_result(req_id, {})
    if method == "tools/list":
        tools = [tool_for(op, site["title"]) for op in (site["spec"]["operations"] if site else [])]
        return rpc_result(req_id, {"tools": tools})
    if method == "tools/call":
        name, args = params.get("name"), params.get("arguments") or {}
        try:
            output, meta = await gateway.execute(conn, name, args, base_url)
            return rpc_result(req_id, {
                "content": [{"type": "text", "text": json.dumps(output, default=str)[:100_000]}],
                "structuredContent": output if isinstance(output, dict) else {"result": output},
                "isError": False,
            })
        except gateway.GatewayError as e:
            err = {"error": e.code, "message": e.message, **e.extra}
            return rpc_result(req_id, {"content": [{"type": "text", "text": json.dumps(err)}], "isError": True})
    if req_id is None:
        return None  # notification (e.g. notifications/initialized): no response
    return rpc_error(req_id, -32601, f"method not found: {method}")


@router.post("/mcp/{api_key}")
async def mcp_post(api_key: str, request: Request):
    try:
        conn = gateway.connection_for_key(api_key)
    except gateway.GatewayError:
        return JSONResponse(rpc_error(None, -32001, "unknown API key"), status_code=401)
    base_url = str(request.base_url).rstrip("/").replace("http://", "https://")
    try:
        body = await request.json()
    except ValueError:
        return JSONResponse(rpc_error(None, -32700, "parse error"), status_code=400)
    if isinstance(body, list):
        out = [r for r in [await handle(m, conn, base_url) for m in body] if r is not None]
        return JSONResponse(out) if out else Response(status_code=202)
    out = await handle(body, conn, base_url)
    return JSONResponse(out) if out is not None else Response(status_code=202)


@router.get("/mcp/{api_key}")
async def mcp_get(api_key: str):
    # No server-initiated stream; clients fall back to plain request/response.
    return Response(status_code=405, headers={"Allow": "POST"})


@router.delete("/mcp/{api_key}")
async def mcp_delete(api_key: str):
    return Response(status_code=204)
